### ISSUE TITLE
Create a discipline

### ISSUE THREAD

**Issue by viniosilva** [viniosilva/kairos-manager#3]
Given a user
When inserting a name
Then create a discipline

### Tasks

- [x] Add default Nest.js structure
- [x] Add discipline module
- [x] Configure Postgres local
- [x] Save a discipline
